services:
    toxyy.acpmergechildforums.controller.acp:
        class: toxyy\acpmergechildforums\controller\acp_controller
        arguments:
            - '@dbal.conn'

    toxyy.acpmergechildforums.listener:
        class: toxyy\acpmergechildforums\event\listener
        arguments:
            - '@language'
            - '@request'
            - '@toxyy.acpmergechildforums.controller.acp'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }