services:
    toxyy.acpmergechildforums.controller.acp:
        class: toxyy\acpmergechildforums\controller\acp_controller
        arguments:
            - '@auth'
            - '@cache.driver'

    toxyy.acpmergechildforums.listener:
        class: toxyy\acpmergechildforums\event\listener
        arguments:
            - '@language'
            - '@request'
            - '@toxyy.acpmergechildforums.controller.acp'
        tags:
            - { name: event.listener }